"""Single place where every API response is validated.

Before this module each test wrote its own `assert response.status == ...` plus an
ad-hoc echo check, so the same assertions existed in four files with four different
failure messages. `validate_response()` replaces all of them: it checks the whole
contract in one call and reports **every** violation at once, so one run tells you
everything that is wrong with a response instead of only the first problem.

What can be validated
    status code .......... expected_status
    content type ......... json_body=True (default) - must be application/json
    JSON schema .......... schema / schema_name  (api/schemas.py)
    request echo ......... echo={"name": ..., "job": ...} - the API must return what was sent
    exact values ......... equals={"error": "Missing password"}
    generated fields ..... non_empty=("id",)
    timestamps ........... recent=("createdAt",) - valid ISO-8601 and close to now
    empty body ........... empty_body=True (204 No Content)
    response time ........ max_response_ms

Typical use:

    body = validate_response(
        response,
        expected_status=201,
        schema=CREATED_USER,
        schema_name="created user",
        echo=payload,
        non_empty=("id",),
        recent=("createdAt",),
    )
"""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any, Iterable, Optional, Sequence

from api.base_client import ApiResponse
from api.schemas import assert_schema
from utils.logger import get_logger

log = get_logger("api.validators")

# A generated timestamp may legitimately differ from the local clock by this much.
MAX_TIMESTAMP_SKEW = timedelta(days=1)


# ============================================================================ single checks
def check_status(response: ApiResponse, expected: int) -> Optional[str]:
    if response.status == expected:
        return None
    return (
        f"status code is {response.status}, expected {expected} "
        f"(body: {response.text[:200] or '<empty>'})"
    )


def check_json_content_type(response: ApiResponse) -> Optional[str]:
    content_type = str(response.headers.get("content-type", ""))
    if "json" in content_type.lower():
        return None
    return f"content-type is {content_type or '<missing>'}, expected application/json"


def check_empty_body(response: ApiResponse) -> Optional[str]:
    if response.text.strip() == "":
        return None
    return f"body should be empty, got {response.text[:200]!r}"


def check_echo(body: Any, expected: dict[str, Any]) -> list[str]:
    """Every field sent in the request must come back with exactly the same value."""
    if not isinstance(body, dict):
        return [f"cannot compare the request payload: the body is {type(body).__name__}, not an object"]
    return [
        f"field {field!r}: sent {value!r}, API returned {body.get(field)!r}"
        for field, value in expected.items()
        if body.get(field) != value
    ]


def check_non_empty(body: Any, fields: Iterable[str]) -> list[str]:
    """Server-generated fields (ids, tokens) must be present and not blank."""
    if not isinstance(body, dict):
        return [f"cannot read fields {list(fields)}: the body is {type(body).__name__}, not an object"]
    problems = []
    for field in fields:
        if field not in body:
            problems.append(f"field {field!r} is missing from the response")
        elif not str(body[field]).strip():
            problems.append(f"field {field!r} is empty ({body[field]!r})")
    return problems


def check_timestamp(body: Any, field: str) -> Optional[str]:
    """The field must be a valid ISO-8601 timestamp that was generated just now."""
    if not isinstance(body, dict) or field not in body:
        return f"timestamp {field!r} is missing from the response"
    raw = str(body[field])
    try:
        stamp = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return f"timestamp {field!r} is not valid ISO-8601: {raw!r}"
    if stamp.tzinfo is None:
        stamp = stamp.replace(tzinfo=timezone.utc)
    age = abs(datetime.now(timezone.utc) - stamp)
    if age > MAX_TIMESTAMP_SKEW:
        return (
            f"timestamp {field!r} is {age} away from now ({raw!r}) - "
            "it should be generated by this request"
        )
    return None


def check_response_time(response: ApiResponse, max_ms: float) -> Optional[str]:
    if response.elapsed_ms <= max_ms:
        return None
    return f"response took {response.elapsed_ms:.0f} ms, the limit is {max_ms:.0f} ms"


# ============================================================================ full validation
def validate_response(
    response: ApiResponse,
    *,
    expected_status: int,
    schema: Optional[dict] = None,
    schema_name: str = "response",
    echo: Optional[dict[str, Any]] = None,
    non_empty: Sequence[str] = (),
    recent: Sequence[str] = (),
    equals: Optional[dict[str, Any]] = None,
    empty_body: bool = False,
    json_body: bool = True,
    max_response_ms: Optional[float] = None,
) -> Any:
    """Validate a complete API response and return the parsed body (None for 204).

    Every check that fails is collected, so a single failure message describes the
    whole problem instead of stopping at the first mismatch.
    """
    problems: list[str] = [p for p in (check_status(response, expected_status),) if p]
    body: Any = None

    if empty_body:
        problem = check_empty_body(response)
        if problem:
            problems.append(problem)
    elif json_body:
        problem = check_json_content_type(response)
        if problem:
            problems.append(problem)
        try:
            body = response.json()
        except (AssertionError, json.JSONDecodeError, ValueError) as error:
            problems.append(f"body is not valid JSON ({error}): {response.text[:200]!r}")
            body = None

    if body is not None:
        if schema is not None:
            try:
                assert_schema(body, schema, schema_name)
            except AssertionError as error:
                problems.append(str(error))
        if echo:
            problems.extend(check_echo(body, echo))
        if equals:
            problems.extend(check_echo(body, equals))
        problems.extend(check_non_empty(body, non_empty))
        problems.extend(p for p in (check_timestamp(body, f) for f in recent) if p)

    if max_response_ms is not None:
        problem = check_response_time(response, max_response_ms)
        if problem:
            problems.append(problem)

    if problems:
        raise AssertionError(
            f"{response.method} {response.url} did not meet the response contract:\n"
            + "\n".join(f"  - {problem}" for problem in problems)
        )

    log.info(
        "%s %s validated: %s in %.0f ms%s",
        response.method,
        response.url,
        response.status,
        response.elapsed_ms,
        f" ({schema_name})" if schema is not None else "",
    )
    return body
